vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        projectfiles_files:
            uri_prefix: '%app.path.projectfiles%'
            upload_destination: '%kernel.project_dir%/public%app.path.projectfiles%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        postfiles_files:
            uri_prefix: '%app.path.postfiles%'
            upload_destination: '%kernel.project_dir%/public%app.path.postfiles%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        gallery_images:
            uri_prefix: '%app.path.postfiles%'
            upload_destination: '%kernel.project_dir%/public%app.path.galleryimages%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer