monolog:
    channels: ['request']
    handlers:
        # main:
        #     type: fingers_crossed
        #     action_level: error
        #     handler: nested
        #     excluded_http_codes: [404, 405]
        #     buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        # nested:
        #     type: stream
        #     path: php://stderr
        #     level: debug
        #     formatter: monolog.formatter.json
        # console:
        #     type: console
        #     process_psr_3_messages: false
        #     channels: ["!event", "!doctrine"]
        request:
            # log all messages (since debug is the lowest level)
            level:    critical
            type:  rotating_file
            max_files: 30
            path:     '%kernel.logs_dir%/request/request.log'
            channels: ["request"]
